#!/bin/sh
set -e
set -u

# アプリケーションのルートディレクトリを指定
APPLICATION_ROOT="/home/fortinet_tacjp/forti_tools"

# オプション設定
# 下記はデフォルトの値。変更したい場合は適宜編集
PORT="80"
BINDING_IP="0.0.0.0"
ENVIRONMENT="prod"

start () {
  cd ${APPLICATION_ROOT}
  nohup php app/console server:run --env=${ENVIRONMENT} ${BINDING_IP}:${PORT} &
}

stop () {
  kill %`jobs | grep 'nohup php app/console' | cut -c 2`
}

restart () {
  stop
  start
}

status () {
  STATUS=`jobs | grep 'nohup php app/console' | cut -c 2`
  if [ -n "$STATUS" ]; then
    echo "Running..."
  else
    echo "Stop!"
  fi
}

help () {
  echo "Usage: $0 {start|stop|restart|status|help}"
}

# 引数のサイズをチェック
# set -u と $1を併用するためのhack
# http://tech.lampetty.net/tech/index.php/archives/455
if [ $# -lt 1 ]; then
    help
    exit 1
fi

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    restart
    ;;
  status)
    status
    ;;
  help)
    help
    ;;
  *)
    help
    exit 1
esac

exit $?